### ISSUE TITLE
Ansible version 2.5

### ISSUE THREAD

**Issue by jabelk** [NSO-developer/nso-ansible-demo#2]
I assume this requires Ansible 2.5, which is not currently full release:

JABELK-M-D3BK:nso-run jabelk$ pip install ansible==2.5
Collecting ansible==2.5
  Could not find a version that satisfies the requirement ansible==2.5 (from versions: 1.0, 1.1, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.6, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.6.10, 1.7, 1.7.1, 1.7.2, 1.8, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.9.0.1, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 1.9.6, 2.0.0.0, 2.0.0.1, 2.0.0.2, 2.0.1.0, 2.0.2.0, 2.1.0.0, 2.1.1.0, 2.1.2.0, 2.1.3.0, 2.1.4.0, 2.1.5.0, 2.1.6.0, 2.2.0.0, 2.2.1.0, 2.2.2.0, 2.2.3.0, 2.3.0.0, 2.3.1.0, 2.3.2.0, 2.3.3.0, 2.4.0.0, 2.4.1.0, 2.4.2.0, 2.4.3.0, 2.5.0a1, 2.5.0b1, 2.5.0b2, 2.5.0rc1)
No matching distribution found for ansible==2.5
JABELK-M-D3BK:nso-run jabelk$

 2.5.0a1, 2.5.0b1, 2.5.0b2, 2.5.0rc1 are valid options, but may be worth calling out in the docs requires ansible==2.5.0+

**Comment by cmoberg** [comment]
Yes, yes it does. I will make a note in the README about this little tiny detail :-)
